# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_DialogParametre.ui'
#
# Created: Wed Jun  4 12:01:45 2014
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DialogParametre(object):
    def setupUi(self, DialogParametre):
        DialogParametre.setObjectName("DialogParametre")
        DialogParametre.resize(401, 290)
        self.layoutWidget = QtGui.QWidget(DialogParametre)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 13, 378, 267))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_Main = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_Main.setObjectName("verticalLayout_Main")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_Nom = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Nom.setMaxLength(60)
        self.lineEdit_Nom.setObjectName("lineEdit_Nom")
        self.horizontalLayout_3.addWidget(self.lineEdit_Nom)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_Remarque = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_Remarque.setMaxLength(200)
        self.lineEdit_Remarque.setObjectName("lineEdit_Remarque")
        self.horizontalLayout_4.addWidget(self.lineEdit_Remarque)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_isQuantitatif = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_isQuantitatif.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_isQuantitatif.setObjectName("checkBox_isQuantitatif")
        self.horizontalLayout_2.addWidget(self.checkBox_isQuantitatif)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_Main.addLayout(self.verticalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(376, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_Main.addItem(spacerItem1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_Unite = QtGui.QLabel(self.layoutWidget)
        self.label_Unite.setObjectName("label_Unite")
        self.horizontalLayout_6.addWidget(self.label_Unite)
        self.comboBox_Unite = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_Unite.setEnabled(True)
        self.comboBox_Unite.setMinimumSize(QtCore.QSize(100, 27))
        self.comboBox_Unite.setMaximumSize(QtCore.QSize(16777215, 27))
        self.comboBox_Unite.setEditable(False)
        self.comboBox_Unite.setObjectName("comboBox_Unite")
        self.horizontalLayout_6.addWidget(self.comboBox_Unite)
        self.toolButton_Unite = QtGui.QToolButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/edit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Unite.setIcon(icon)
        self.toolButton_Unite.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_Unite.setObjectName("toolButton_Unite")
        self.horizontalLayout_6.addWidget(self.toolButton_Unite)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.label_Min = QtGui.QLabel(self.layoutWidget)
        self.label_Min.setMinimumSize(QtCore.QSize(80, 0))
        self.label_Min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Min.setObjectName("label_Min")
        self.gridLayout.addWidget(self.label_Min, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 2)
        self.label_Max = QtGui.QLabel(self.layoutWidget)
        self.label_Max.setMinimumSize(QtCore.QSize(80, 0))
        self.label_Max.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Max.setObjectName("label_Max")
        self.gridLayout.addWidget(self.label_Max, 0, 5, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 6, 1, 2)
        self.label_Norme = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_Norme.setFont(font)
        self.label_Norme.setObjectName("label_Norme")
        self.gridLayout.addWidget(self.label_Norme, 1, 0, 1, 1)
        self.lineEdit_NormMin = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_NormMin.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_NormMin.setText("")
        self.lineEdit_NormMin.setMaxLength(8)
        self.lineEdit_NormMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_NormMin.setReadOnly(False)
        self.lineEdit_NormMin.setObjectName("lineEdit_NormMin")
        self.gridLayout.addWidget(self.lineEdit_NormMin, 1, 1, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 3, 1, 1)
        self.lineEdit_NormMax = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_NormMax.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_NormMax.setMaxLength(8)
        self.lineEdit_NormMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_NormMax.setObjectName("lineEdit_NormMax")
        self.gridLayout.addWidget(self.lineEdit_NormMax, 1, 4, 1, 3)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 7, 1, 1)
        self.verticalLayout_Main.addLayout(self.gridLayout)
        spacerItem8 = QtGui.QSpacerItem(376, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_Main.addItem(spacerItem8)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_Cancel = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_5.addWidget(self.pushButton_Cancel)
        self.pushButton_Add = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.horizontalLayout_5.addWidget(self.pushButton_Add)
        self.pushButton_Delete = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.horizontalLayout_5.addWidget(self.pushButton_Delete)
        self.pushButton_Valid = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Valid.setObjectName("pushButton_Valid")
        self.horizontalLayout_5.addWidget(self.pushButton_Valid)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_5)
        self.label.setBuddy(self.lineEdit_Nom)
        self.label_2.setBuddy(self.lineEdit_Remarque)
        self.label_Unite.setBuddy(self.comboBox_Unite)
        self.label_Min.setBuddy(self.lineEdit_NormMin)
        self.label_Max.setBuddy(self.lineEdit_NormMax)

        self.retranslateUi(DialogParametre)
        QtCore.QMetaObject.connectSlotsByName(DialogParametre)

    def retranslateUi(self, DialogParametre):
        DialogParametre.setWindowTitle(QtGui.QApplication.translate("DialogParametre", "OpenVet", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DialogParametre", "Paramètre :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DialogParametre", "Remarque :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_isQuantitatif.setText(QtGui.QApplication.translate("DialogParametre", "Quantitatif", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Unite.setText(QtGui.QApplication.translate("DialogParametre", "Unité :", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Unite.setText(QtGui.QApplication.translate("DialogParametre", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Min.setText(QtGui.QApplication.translate("DialogParametre", "Minimum :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Max.setText(QtGui.QApplication.translate("DialogParametre", "Maximum :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Norme.setText(QtGui.QApplication.translate("DialogParametre", "Norme :", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Cancel.setText(QtGui.QApplication.translate("DialogParametre", "Annuler", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Add.setText(QtGui.QApplication.translate("DialogParametre", "Nouveau", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Delete.setText(QtGui.QApplication.translate("DialogParametre", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Valid.setText(QtGui.QApplication.translate("DialogParametre", "Valider", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
