# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Form_openvet.ui'
#
# Created: Sat Jun 13 23:04:31 2015
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 679)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("None")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_fiches = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_fiches.setGeometry(QtCore.QRect(2, 2, 1076, 181))
        self.tabWidget_fiches.setToolTip("")
        self.tabWidget_fiches.setAutoFillBackground(False)
        self.tabWidget_fiches.setStyleSheet("None")
        self.tabWidget_fiches.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_fiches.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_fiches.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_fiches.setTabsClosable(True)
        self.tabWidget_fiches.setObjectName("tabWidget_fiches")
        self.tab_fiche1 = QtGui.QWidget()
        self.tab_fiche1.setObjectName("tab_fiche1")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_fiche1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LayoutFicheHead = QtGui.QHBoxLayout()
        self.LayoutFicheHead.setObjectName("LayoutFicheHead")
        self.frame_client = QtGui.QFrame(self.tab_fiche1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_client.sizePolicy().hasHeightForWidth())
        self.frame_client.setSizePolicy(sizePolicy)
        self.frame_client.setBaseSize(QtCore.QSize(520, 120))
        self.frame_client.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_client.setFrameShape(QtGui.QFrame.Box)
        self.frame_client.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_client.setLineWidth(1)
        self.frame_client.setObjectName("frame_client")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_client)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_client = MyComboBox(self.frame_client)
        self.comboBox_client.setMinimumSize(QtCore.QSize(350, 27))
        self.comboBox_client.setMaximumSize(QtCore.QSize(500, 27))
        self.comboBox_client.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_client.setEditable(True)
        self.comboBox_client.setObjectName("comboBox_client")
        self.horizontalLayout.addWidget(self.comboBox_client)
        self.toolButton_editClient = QtGui.QToolButton(self.frame_client)
        self.toolButton_editClient.setMaximumSize(QtCore.QSize(26, 26))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/edit1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_editClient.setIcon(icon1)
        self.toolButton_editClient.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editClient.setObjectName("toolButton_editClient")
        self.horizontalLayout.addWidget(self.toolButton_editClient)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButton_ClientInfo = QtGui.QToolButton(self.frame_client)
        self.toolButton_ClientInfo.setMaximumSize(QtCore.QSize(30, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClientInfo.setIcon(icon2)
        self.toolButton_ClientInfo.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_ClientInfo.setObjectName("toolButton_ClientInfo")
        self.horizontalLayout.addWidget(self.toolButton_ClientInfo)
        self.toolButton_scan1 = QtGui.QToolButton(self.frame_client)
        self.toolButton_scan1.setMaximumSize(QtCore.QSize(30, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/loupe2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_scan1.setIcon(icon3)
        self.toolButton_scan1.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_scan1.setObjectName("toolButton_scan1")
        self.horizontalLayout.addWidget(self.toolButton_scan1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBrowser_client = QtGui.QTextBrowser(self.frame_client)
        self.textBrowser_client.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_client.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textBrowser_client.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_client.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_client.setLineWidth(1)
        self.textBrowser_client.setMidLineWidth(0)
        self.textBrowser_client.setObjectName("textBrowser_client")
        self.verticalLayout_2.addWidget(self.textBrowser_client)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.LayoutFicheHead.addWidget(self.frame_client)
        self.frame_animal = QtGui.QFrame(self.tab_fiche1)
        self.frame_animal.setBaseSize(QtCore.QSize(520, 120))
        self.frame_animal.setStyleSheet("background-color: rgb(188, 255, 231,0);")
        self.frame_animal.setFrameShape(QtGui.QFrame.Box)
        self.frame_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_animal.setObjectName("frame_animal")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_animal)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_Animal = MyComboBox(self.frame_animal)
        self.comboBox_Animal.setMinimumSize(QtCore.QSize(320, 27))
        self.comboBox_Animal.setMaximumSize(QtCore.QSize(500, 27))
        self.comboBox_Animal.setStyleSheet("selection-background-color: rgb(255, 255, 127);")
        self.comboBox_Animal.setEditable(True)
        self.comboBox_Animal.setObjectName("comboBox_Animal")
        self.horizontalLayout_2.addWidget(self.comboBox_Animal)
        self.toolButton_editAnimal = QtGui.QToolButton(self.frame_animal)
        self.toolButton_editAnimal.setMaximumSize(QtCore.QSize(26, 26))
        self.toolButton_editAnimal.setIcon(icon1)
        self.toolButton_editAnimal.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_editAnimal.setObjectName("toolButton_editAnimal")
        self.horizontalLayout_2.addWidget(self.toolButton_editAnimal)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.toolButton_Relance = QtGui.QToolButton(self.frame_animal)
        self.toolButton_Relance.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_Relance.setMaximumSize(QtCore.QSize(30, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/relance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Relance.setIcon(icon4)
        self.toolButton_Relance.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_Relance.setObjectName("toolButton_Relance")
        self.horizontalLayout_2.addWidget(self.toolButton_Relance)
        self.toolButton_Poids = QtGui.QToolButton(self.frame_animal)
        self.toolButton_Poids.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_Poids.setMaximumSize(QtCore.QSize(30, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/mesures.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Poids.setIcon(icon5)
        self.toolButton_Poids.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_Poids.setObjectName("toolButton_Poids")
        self.horizontalLayout_2.addWidget(self.toolButton_Poids)
        self.toolButton_scan2 = QtGui.QToolButton(self.frame_animal)
        self.toolButton_scan2.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_scan2.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_scan2.setIcon(icon3)
        self.toolButton_scan2.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_scan2.setObjectName("toolButton_scan2")
        self.horizontalLayout_2.addWidget(self.toolButton_scan2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser_animal = QtGui.QTextBrowser(self.frame_animal)
        self.textBrowser_animal.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser_animal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_animal.setToolTip("")
        self.textBrowser_animal.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textBrowser_animal.setFrameShape(QtGui.QFrame.Box)
        self.textBrowser_animal.setFrameShadow(QtGui.QFrame.Raised)
        self.textBrowser_animal.setObjectName("textBrowser_animal")
        self.verticalLayout.addWidget(self.textBrowser_animal)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.LayoutFicheHead.addWidget(self.frame_animal)
        self.verticalLayout_5.addLayout(self.LayoutFicheHead)
        self.tabWidget_fiches.addTab(self.tab_fiche1, "")
        self.tab_fiche2 = QtGui.QWidget()
        self.tab_fiche2.setEnabled(True)
        self.tab_fiche2.setObjectName("tab_fiche2")
        self.tabWidget_fiches.addTab(self.tab_fiche2, "")
        self.tab_new = QtGui.QWidget()
        self.tab_new.setObjectName("tab_new")
        self.tabWidget_fiches.addTab(self.tab_new, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 23))
        self.menubar.setObjectName("menubar")
        self.menuDossiers_M_dicaux = QtGui.QMenu(self.menubar)
        self.menuDossiers_M_dicaux.setObjectName("menuDossiers_M_dicaux")
        self.menuComptabilit = QtGui.QMenu(self.menubar)
        self.menuComptabilit.setObjectName("menuComptabilit")
        self.menuD_clarations = QtGui.QMenu(self.menuComptabilit)
        self.menuD_clarations.setObjectName("menuD_clarations")
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuBase_de_donn_es = QtGui.QMenu(self.menuConfiguration)
        self.menuBase_de_donn_es.setObjectName("menuBase_de_donn_es")
        self.menuQuitter = QtGui.QMenu(self.menubar)
        self.menuQuitter.setObjectName("menuQuitter")
        self.menuStock = QtGui.QMenu(self.menubar)
        self.menuStock.setObjectName("menuStock")
        self.menuStatistiques = QtGui.QMenu(self.menubar)
        self.menuStatistiques.setObjectName("menuStatistiques")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Recettes = QtGui.QAction(MainWindow)
        self.action_Recettes.setObjectName("action_Recettes")
        self.actionD_penses = QtGui.QAction(MainWindow)
        self.actionD_penses.setObjectName("actionD_penses")
        self.action_Banque = QtGui.QAction(MainWindow)
        self.action_Banque.setObjectName("action_Banque")
        self.actionRecoupement_bancaire = QtGui.QAction(MainWindow)
        self.actionRecoupement_bancaire.setObjectName("actionRecoupement_bancaire")
        self.actionTVA = QtGui.QAction(MainWindow)
        self.actionTVA.setObjectName("actionTVA")
        self.action2035 = QtGui.QAction(MainWindow)
        self.action2035.setObjectName("action2035")
        self.actionCommandes = QtGui.QAction(MainWindow)
        self.actionCommandes.setObjectName("actionCommandes")
        self.actionAnalyse = QtGui.QAction(MainWindow)
        self.actionAnalyse.setObjectName("actionAnalyse")
        self.action_Facturation = QtGui.QAction(MainWindow)
        self.action_Facturation.setObjectName("action_Facturation")
        self.actionBureau = QtGui.QAction(MainWindow)
        self.actionBureau.setObjectName("actionBureau")
        self.action_M_dicaments = QtGui.QAction(MainWindow)
        self.action_M_dicaments.setObjectName("action_M_dicaments")
        self.action_Pathologies = QtGui.QAction(MainWindow)
        self.action_Pathologies.setObjectName("action_Pathologies")
        self.actionBackup = QtGui.QAction(MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actionRestore = QtGui.QAction(MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionR_seau_S_curit = QtGui.QAction(MainWindow)
        self.actionR_seau_S_curit.setObjectName("actionR_seau_S_curit")
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuD_clarations.addAction(self.actionTVA)
        self.menuD_clarations.addAction(self.action2035)
        self.menuComptabilit.addAction(self.action_Recettes)
        self.menuComptabilit.addAction(self.actionD_penses)
        self.menuComptabilit.addAction(self.action_Banque)
        self.menuComptabilit.addAction(self.actionRecoupement_bancaire)
        self.menuComptabilit.addAction(self.menuD_clarations.menuAction())
        self.menuBase_de_donn_es.addAction(self.actionBackup)
        self.menuBase_de_donn_es.addAction(self.actionRestore)
        self.menuBase_de_donn_es.addAction(self.actionImport)
        self.menuConfiguration.addAction(self.actionBureau)
        self.menuConfiguration.addAction(self.action_Facturation)
        self.menuConfiguration.addAction(self.action_M_dicaments)
        self.menuConfiguration.addAction(self.action_Pathologies)
        self.menuConfiguration.addSeparator()
        self.menuConfiguration.addAction(self.menuBase_de_donn_es.menuAction())
        self.menuConfiguration.addAction(self.actionR_seau_S_curit)
        self.menuQuitter.addAction(self.actionQuitter)
        self.menuStock.addAction(self.actionCommandes)
        self.menuStock.addAction(self.actionAnalyse)
        self.menubar.addAction(self.menuDossiers_M_dicaux.menuAction())
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuComptabilit.menuAction())
        self.menubar.addAction(self.menuStatistiques.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuQuitter.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_fiches.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Open Vet", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_client.setToolTip(QtGui.QApplication.translate("MainWindow", "Sélection Client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editClient.setToolTip(QtGui.QApplication.translate("MainWindow", "Modifie client", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editClient.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_ClientInfo.setToolTip(QtGui.QApplication.translate("MainWindow", "Informations complémentaires", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_ClientInfo.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan1.setToolTip(QtGui.QApplication.translate("MainWindow", "Recherche client / animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan1.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_client.setToolTip(QtGui.QApplication.translate("MainWindow", "Double click pour sélectionner l\'édition", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Animal.setToolTip(QtGui.QApplication.translate("MainWindow", "Selection Animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editAnimal.setToolTip(QtGui.QApplication.translate("MainWindow", "Modifie animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_editAnimal.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Relance.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Poids.setToolTip(QtGui.QApplication.translate("MainWindow", "poids et mesures", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Poids.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan2.setToolTip(QtGui.QApplication.translate("MainWindow", "Recherche client / animal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_scan2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_fiche1), QtGui.QApplication.translate("MainWindow", "Client1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_fiche2), QtGui.QApplication.translate("MainWindow", "Client2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_fiches.setTabText(self.tabWidget_fiches.indexOf(self.tab_new), QtGui.QApplication.translate("MainWindow", "Ajouter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDossiers_M_dicaux.setTitle(QtGui.QApplication.translate("MainWindow", "Dossiers Médicaux", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComptabilit.setTitle(QtGui.QApplication.translate("MainWindow", "Comptabilité", None, QtGui.QApplication.UnicodeUTF8))
        self.menuD_clarations.setTitle(QtGui.QApplication.translate("MainWindow", "Déclarations", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguration.setTitle(QtGui.QApplication.translate("MainWindow", "Paramètres", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBase_de_donn_es.setTitle(QtGui.QApplication.translate("MainWindow", "Base de données", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuitter.setTitle(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStock.setTitle(QtGui.QApplication.translate("MainWindow", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStatistiques.setTitle(QtGui.QApplication.translate("MainWindow", "Statistiques", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Recettes.setText(QtGui.QApplication.translate("MainWindow", "&Recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionD_penses.setText(QtGui.QApplication.translate("MainWindow", "&Dépenses", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Banque.setText(QtGui.QApplication.translate("MainWindow", "&Banque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecoupement_bancaire.setText(QtGui.QApplication.translate("MainWindow", "Recoupement bancaire", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTVA.setText(QtGui.QApplication.translate("MainWindow", "TVA", None, QtGui.QApplication.UnicodeUTF8))
        self.action2035.setText(QtGui.QApplication.translate("MainWindow", "2035", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommandes.setText(QtGui.QApplication.translate("MainWindow", "&Commandes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnalyse.setText(QtGui.QApplication.translate("MainWindow", "Visualisation", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Facturation.setText(QtGui.QApplication.translate("MainWindow", "&Facturation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setText(QtGui.QApplication.translate("MainWindow", "Bureau", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBureau.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+B", None, QtGui.QApplication.UnicodeUTF8))
        self.action_M_dicaments.setText(QtGui.QApplication.translate("MainWindow", "&Médicaments", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Pathologies.setText(QtGui.QApplication.translate("MainWindow", "&Pathologies", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackup.setText(QtGui.QApplication.translate("MainWindow", "Backup", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore.setText(QtGui.QApplication.translate("MainWindow", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionR_seau_S_curit.setText(QtGui.QApplication.translate("MainWindow", "Réseau/Sécurité", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setToolTip(QtGui.QApplication.translate("MainWindow", "Quitter l\'application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

from Mywidgets import MyComboBox
import resources_rc
